version: "3.8"
services:
  fastapi_app:
    build: ./recipe_app_backend
    ports:
      - "8000:8000"
    environment:
      - SPOONACULAR_MICROSERVICE_URL=http://spoonacular:8001
      - DATABASE_URL=http://database:8002
    depends_on:
      - spoonacular
      - database

  spoonacular:
    build: ./spoonacular
    ports:
      - "8001:8001"

  database:
    build: ./database
    ports:
      - "8002:8002"
    environment:
      - SECRET_KEY=LySv4cLESCDuwoeHb9XW3vEsQQ7AB8AR7fcKzl0CO3Y=
      - ALGORITHM=HS256
  frontend:
    build: ./recipe_app_frontend/app
    ports:
      - "3000:80"
    depends_on:
      - fastapi_app
